### ISSUE TITLE
reset.css常规重置样式

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#10]
```css
@charset "utf-8";
body,ul,li,p,h1,h2,h3,h4,h5,h6,form,fieldset,table,td,img,div,dl,dt,dd,input{margin:0;padding:0;}
body{font-size:12px;}
img{border:none;}
li{list-style:none;}
input,select,textarea{outline:none;}
textarea{resize:none;}
a{text-decoration:none;}
input{border:none;}

/*清除浮动*/
.clearfix:after{content:"";display:block;clear:both;}
.clearfix{zoom:1;}
```
