### ISSUE TITLE
有icon小图标的span, 要设置宽高，也要设置display:inline-block

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#17]
span的常见用处是设置一个小的icon图标，如下所示
```css
.btn span {
    width:5px;
    height:8px;
    display:inline-block;
    background:url('../images/icon/triangle.png')left center no-repeat;
}
```
要是宽高起作用，需要设置span为inline-block，因为span默认是行级元素，行级元素没有宽高
