### ISSUE TITLE
清除浮动最终版

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#28]
几种清楚浮动的方式：
1. 在父容器最后加`<div style="clear:both;"></div>`
2. 父容器设置`overflow:auto`或者`overflow:hidden`
3. 父容器本身也设置浮动`float:left`
4. 使用伪类
```css
.clearfix:before,   
.clearfix:after {
    content: '';
    display: table; 
}

.clearfix:after {
    clear: both;
}

```

在线演示：[清除浮动](http://codepen.io/ckinmind/pen/rjNoaW)

**Comment by ckinmind** [comment]
1. 清楚浮动的核心思想都是触发一个BFC来达到撑开父容器的目的
2. 关于使用伪类清楚浮动
```css
.clearfix:after {
   content:'.';
   display:block;
   height:0;
   clear: both;
   visibility:hidden;
}
.clearfix {
  zoom:1;
}
```
>最下面的zoom:1是为了兼容ie6/7，这样设置会触发其haslayout，haslayout才能清楚浮动

3. 更多设置
```
给父容器设置
display:table-cell;
display:inline-block;
position:fixed
position:absolute;
这些都可以触发BFC
```

4. 最终的清除浮动方案
```css
.clearfix:before,   /*before是为了方式上下margin合并*/
.clearfix:after {
    content: '';
    display: table;  /*创建匿名表格单元触发BFC*/
}

.clearfix:after {
    clear: both;
}
```
