### ISSUE TITLE
.clearfix {*zoom:1;}

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#3]
在用less写微博的教程里看到的，完整的css代码如下：
```css
 .content {
  margin: 0 auto;
  width: 1240px;
  *zoom: 1;
}
.content:before,
.content:after {
  display: table;
  content: "";
}
.content:after {
  clear: both;
}
```
用于清楚浮动
