### ISSUE TITLE
Scss中import Scss文件的顺序是有影响的

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#41]
场景如下：
```css
// index.scss中
import "toolbar";
import "mixin" ;

// mixin.scss中
@mixin transition($value) {
    -webkit-transition: $value;
    -moz-transition: $value;
    -ms-transition: $value;
    -o-transition: $value;
    transition: $value;
}

//toolbar.scss中
.toolbar-text {
   @include transition(all 1s);  
}
```
结果编译的时候报错，告知toolbar.scss没有找到transition，最后查找原因发现是因为index.scss中的import的顺序的影响，先import mixin 在import toolbar就没问题了
