### ISSUE TITLE
-webkit-margin-before: 1em;

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#44]
发现chrome浏览器有给ul一个默认样式，如下
```css
ul, menu, dir {
    display: block;
    list-style-type: disc;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 40px;
}
```
1.  -webkit-margin-before:1em    是元素上边距数值为1倍字体高度    即字体高为10px的话，上边距就为10px   
2. 重置样式时ul{margin:0;padding:0}并不能清除这个默认样式
