### ISSUE TITLE
 font: 0/0 a;当中的a是什么意思

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#46]
看到一个隐藏文字的样式有这种写法
```css
.text-hide {
    font: 0/0 a;
    color: transparent;
    text-shadow: none;
    background-color: transparent;
    border: 0;
}
```
>a是个最短的字体名称，但不可能客户端有装这个名称的字体，只是用来为了通过css validation的

参考资料：[](http://bbs.blueidea.com/thread-3285943-1-1.html)
