### ISSUE TITLE
通过 transform: translateY(-50%)来实现垂直居中

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#50]
```css
div {
    position: absolute;
    height: 16px;
    right: 90px;
    top: 50%;
    transform: translateY(-50%);
}
```
>` top: 50%;` 只能是上边框距离顶部50%,要想整个居中需要在上移自身高度的50% ,这时可以用` transform: translateY(-50%);` 还可以使用`margin-top: -8px`但是这需要计算高度的一半
