### ISSUE TITLE
设置全局都使用box-sizing: border-box

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#51]
```css
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```
>这样在插件或的其他组件中就能更容易地改变 box-sizing 了

参考资料: [12 个 CSS 高级技巧汇总](http://www.admin10000.com/document/6733.html)
参考资料：[codepen:计算器(有用到这个技巧)](http://codepen.io/mjijackson/pen/xOzyGX?editors=0010)
