### ISSUE TITLE
Firefox中有required属性的input会有默认的红色边框

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#62]
**[问题描述]**：火狐浏览器会给required的input一个默认的红色边框

**[问题解决]**：[Firefox adds red border to required input](https://github.com/react-toolbox/react-toolbox/issues/1639)

```css
input:required {
    box-shadow: none;
}
```
