### ISSUE TITLE
Firfox中点击select会有默认的边框出现

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#63]
**[问题描述]**：原生写的select在火狐里点击后会出现一个边框

**[问题解决]**：[stackoverflow: Cannot remove outline/dotted border from Firefox select drop down 
](https://stackoverflow.com/questions/19451183/cannot-remove-outline-dotted-border-from-firefox-select-drop-down)

```css
select:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #000;
}
option:not(:checked) {
  color: black; /* prevent <option>s from becoming transparent as well */
}
```
