### ISSUE TITLE
解决因为chrome代码回填导致的密码和placeholder重叠的问题

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#64]
**[问题描述]**：因为input的placeholder不是用原生的placeholder实现而是用label实现，然后当chrome有密码回填的时候回发现两者会重叠

**[问题解决]**：如下

```css
input:-webkit-autofill ~ label {
    display: none
}
```
