### ISSUE TITLE
图片填充整个屏幕

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#66]
```css
html { 
  background: url(images/bg.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```
**参考资料**
- [Perfect Full Page Background Image](https://css-tricks.com/perfect-full-page-background-image/)
