### ISSUE TITLE
超出文本的修剪（ white-space/ text-overflow）

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#8]
```css
.title {
    width:230px;
    overflow:hidden;
    white-space:nowrap;
    text-overflow: ellipsis;
}
```
>`white-space`  white-space 属性设置如何处理元素内的空白, 
> `nowrap`文本不会换行，文本会在在同一行上继续，直到遇到 `<br>` 标签为止
>` text-overflow` text-overflow 属性规定当文本溢出包含元素时发生的事情
> `ellipsis` 显示省略符号来代表被修剪的文本

整段css的意思是title样式的宽度230px,不自动换行，超出部分隐藏，如果有超出用省略号代替超出部分
