### ISSUE TITLE
雪碧图定位/小图标转Base64

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/CSSCollect#9]
为了加快图片的访问速度，减少图片的请求，通常会将
1. 小图标合成一张雪碧图
2. 将小图标转成base64

**Comment by ckinmind** [comment]
1. 雪碧图示例
```html
<style>
 .star {
    display:inline-block;
    width:12px;
    height:13px;
    margin-right:5px;
    background:url('../images/star.png') no-repeat;
}

 .nostar {
    background-position: 0 -13px;
}
</style>
 <div class="star-bar">
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star nostar"></span>
 </div>
```
>最终显示五颗星星，四个黄一个灰，通过background-position来定位

**Comment by ckinmind** [comment]
2. base64示例

```css
 .star {
    display:inline-block;
    width:12px;
    height:13px;
    margin-right:5px;
    background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAaCAYAAABsONZfAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2ZpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDowQTMxMzk2QjRFMUJFNDExQTM4RTkwNzk5M0M4MEMxNyIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDoyQ0Q0QjQzMkI5RkUxMUU2Qjg1NkU5NjAyMEUwMTlFMiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDoyQ0Q0QjQzMUI5RkUxMUU2Qjg1NkU5NjAyMEUwMTlFMiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M2IChXaW5kb3dzKSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOkJCOTg0Q0RENUUzMEU0MTFBRkI4Q0I0NjRCMzMzQkE0IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjBBMzEzOTZCNEUxQkU0MTFBMzhFOTA3OTkzQzgwQzE3Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+M/h50gAAAQpJREFUeNpi/HhfigEHYATi/9gkmBhwA2sg1iVVUxQQx2J1Ag7nsQLxMyD+CcRyQPyPGJtcgFgEiKWB2BFdkgVKZwNxABALQvmSSGoWAfFzJP4smKZpQMwMxF1AzI5msBQUfwPiLCBeCHMeKGgnAbENEN/H4txbQGwO0oDNT2eAeB0WTTuB+Aq+gPCG0l+B+DOU7Y8v9JSBWAOITwGxERDrA/FBaLDr49LkDsTN0NRwC+o/JyAuBmI3XJErAMQfQIy3/48wCjPaIKc9HiD+gs2mD8hpD6gROe19gdt07949XGlvGlRhGbEJFpT2QqGJlolYTaNpb5ClPbQUIYCWlBhITXvoAJ72AAIMABbVUF23t48cAAAAAElFTkSuQmCC') no-repeat;
}
 .nostar {
    background-position: 0 -13px;
}
```
